name: Build & Publish Wheel

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'index.html'   # don’t trigger if the only file changed is index.html

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # to push to gh-pages
      pages: write            # to deploy pages
      id-token: write         # for OIDC if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install build tool
        run: pip install build setuptools wheel

      - name: Build wheel
        run: |
          python -m build --wheel --no-isolation

          mv dist/*.whl dist/magUniverse-latest.whl

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Copy wheel into docs/
        run: mv dist/magUniverse-latest.whl docs/magUniverse-latest.whl
    

      - name: Commit & push changes if docs changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage changes
          git add docs/magUniverse-latest.whl
          
          git diff --staged --name-only
          git commit -m "chore: CI update magUniverse-latest.whl"
          git push origin main