name: Build & Publish Wheel

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # to push to gh-pages
      pages: write            # to deploy pages
      id-token: write         # for OIDC if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install build tool
        run: pip install build setuptools wheel

      - name: Build wheel
        run: |
          python -m build --wheel --no-isolation

          mv dist/*.whl dist/magUniverse-latest.whl

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      # upload  the built wheel as the Pages artifact
      - name: Upload wheel artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/magUniverse-latest.whl

      # publish to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
