name: CI Build Wheel, Manifest, Website, and Services

on:
  push:
    branches:
      - main
    paths:
      - 'maguniverse/**'  # detect changes in maguniverse directory only

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      
      - name: Fetch main branch
        run: git fetch origin main

      - name: Check for differences
        run: |
          # Check if there are changes in the docs directory
          if git diff --exit-code origin/main; then
            echo "no_diff=true" >> $GITHUB_OUTPUT
          else
            echo "no_diff=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -e .
      
      # generate manifest.json for collection of getters
      - name: Generate manifest
        run:  python maguniverse/utils/generate_manifest.py
      
      # generate index.html for collection of getters
      - name: Generate documentation
        run:  python maguniverse/utils/docs_out.py

      # build and publish the wheel to docs/
      - name: Install build tool
        run: pip install build setuptools wheel

      - name: Build wheel
        run: |
          python -m build --wheel --no-isolation

          mv dist/*.whl dist/magUniverse-latest-py3-none-any.whl

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Copy wheel into docs/
        run: mv dist/magUniverse-latest-py3-none-any.whl docs/magUniverse-latest-py3-none-any.whl
    
      - name: Commit & push changes if docs changed
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATEKEY }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage changes
          git add .
          
          git diff --staged --name-only
          git commit -m "chore: update index.html; getter manifest"
          git push origin main
          
