name: Update magUniverse Paper Collection HTML

on:
  push:
    branches:
      - main
    paths:
      - 'maguniverse/data/**/__init__.py'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Generate documentation
        run: |
          python maguniverse/utils/docs_out.py

      - name: Commit & push changes if docs changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          # Ensure we're on main and in sync
          git checkout main
          git fetch origin main
          git pull origin main

          # Stage changes
          git add docs/index.html
          
          # Only commit and push if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Auto-update documentation"
          git push origin main
          
