name: Update manifest JSON and magUniverse Paper Collection HTML

on:
  push:
    branches:
      - main
    paths:
      # detect changes in data __init__.py files
      - 'maguniverse/data/**/__init__.py'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -e .
      
      # generate manifest.json before index.html
      - name: Generate manifest
        run:  python maguniverse/utils/generate_manifest.py

      - name: Generate documentation
        run:  python maguniverse/utils/docs_out.py

      - name: Commit & push changes if docs changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Ensure we're on main and in sync
          git checkout main
          git fetch origin main
          git pull origin main

          # Stage changes
          git add docs/index.html
          git add docs/manifest.json
          
          # Only commit and push if there are changes
          git diff --quiet || git commit -m "chore: update index.html; getter manifest"
          git push
          
